import { useAuth } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const { isSignedIn } = useAuth();

  if (isSignedIn) {
    router.push("/dashboard");
  }

  return (
    <>
      <Head>
        <title>Watcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" flex h-screen w-screen items-center justify-center bg-gradient-to-br from-gray-900 via-purple-900 to-violet-700">
        <div className="flex flex-col items-center justify-center gap-4 rounded-md border-2 bg-white p-24 shadow-md">
          <span className="text-5xl">Welcome to Watcher 🍿</span>
          <button
            className="mt-8 w-48 rounded-md bg-blue-600 px-3 py-2 text-white hover:bg-blue-700"
            onClick={() => router.push("/sign-in")}
          >
            Sign In
          </button>
          <button
            className="w-48 rounded-md bg-blue-600 px-3 py-2 text-white hover:bg-blue-700"
            onClick={() => router.push("/sign-up")}
          >
            Create Account
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
